# frozen_string_literal: true

source 'https://rubygems.org'

group :test do
  gem 'rspec'
  gem 'rspec-its'
end

group :development, :test do
  gem 'guard'
  gem 'guard-rspec'
  gem 'relaxed-rubocop'
  gem 'rubocop'
end
