inherit_from:
  - .relaxed-rubocop-2.4.yml

AllCops:
  TargetRubyVersion: 2.6
  UseCache: true
  DefaultFormatter: progress
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
    - "external*/**/*"
    - "bazel-*/**/*"
    - "**/examples/**/*"
    - "**/BUILD"
    - "**/*.bazel"
    - "**/*.bzl"
    - "**/rubocop"
    - "**/vendor/bundle/**/*"
  Include:
    - '**/*.rb'
    - '**/*.gemfile'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*.ru'
    - '**/Gemfile'
    - '**/Rakefile'

Layout/HashAlignment:
  Enabled: true
  EnforcedColonStyle: table
  
Style/Dir:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented_relative_to_receiver

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Naming/MethodParameterName:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

