name: Rubocop
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3.4
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.4.x
    - name: Run Rubocop
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rubocop --enable-pending-cops

